# Copyright (c) 2023 VEXXHOST, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Verify
  hosts: all
  become: true
  pre_tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:

  tasks:
    - name: Assert that the Docker service is still up
      ansible.builtin.assert:
        that:
          - ansible_facts.services["docker.service"].state == "running"
          - ansible_facts.services["docker.service"].status == "enabled"

    - name: Check if Docker version is correct
      command: docker --version
      register: version_output
      ignore_errors: yes
      failed_when: "docker_version not in version_output.stdout"

    - name: Check if docker ps command return 0
      command: docker ps
      register: result
      failed_when: "result.rc !=0"
